/**
 * DTO (Data Transfer Object) type utilities for metal-orm.
 * Derives API types from TableDef/Entity metadata.
 */

import type { TableDef } from '../schema/table.js';
import type { ColumnDef } from '../schema/column-types.js';
import type { ColumnToTs, InferRow } from '../schema/types.js';

/**
 * Utility to flatten intersection types for better IDE display.
 */
export type Simplify<T> = { [K in keyof T]: T[K] } & {};

/**
 * Response DTO - excludes specified columns from the entity.
 * Use this to hide sensitive fields like passwordHash, apiKey, etc.
 *
 * @example
 * ```ts
 * // Exclude passwordHash from response
 * type UserResponse = Dto<typeof User, 'passwordHash'>;
 *
 * // Exclude multiple fields
 * type UserPublic = Dto<typeof User, 'passwordHash' | 'email'>;
 *
 * // Include all fields (no exclusions)
 * type UserFull = Dto<typeof User>;
 * ```
 */
export type Dto<
  T extends TableDef,
  TExclude extends keyof InferRow<T> = never
> = Simplify<Omit<InferRow<T>, TExclude>>;

/**
 * Compose a DTO with relations.
 *
 * @example
 * ```ts
 * type UserWithPosts = WithRelations<UserResponse, {
 *   posts: PostResponse[]
 * }>;
 *
 * type PostWithAuthor = WithRelations<PostResponse, {
 *   author: Dto<typeof User, 'passwordHash' | 'email'>
 * }>;
 * ```
 */
export type WithRelations<TBase, TRelations> = Simplify<TBase & TRelations>;

// ─────────────────────────────────────────────────────────────────────────────
// Column classification helpers for Create/Update DTOs
// ─────────────────────────────────────────────────────────────────────────────

type ColumnMap<T extends TableDef> = T['columns'];

/**
 * Checks if a column has a default value.
 */
type HasDefault<TCol extends ColumnDef> =
  TCol['default'] extends undefined ? false : true;

/**
 * Checks if a column is auto-generated (autoIncrement or generated always/byDefault).
 */
type IsAutoGenerated<TCol extends ColumnDef> =
  TCol['autoIncrement'] extends true ? true :
  TCol['generated'] extends 'always' | 'byDefault' ? true :
  false;

/**
 * Checks if a column is insertable (not auto-generated).
 */
type IsInsertable<TCol extends ColumnDef> =
  IsAutoGenerated<TCol> extends true ? false : true;

/**
 * Checks if a column is required for insert (notNull, no default, not auto-generated).
 */
type IsRequiredInsert<TCol extends ColumnDef> =
  TCol['notNull'] extends true
    ? IsAutoGenerated<TCol> extends true ? false :
      HasDefault<TCol> extends true ? false :
      true
    : false;

/**
 * Keys that are required for insert (notNull, no default, not auto-generated).
 */
type RequiredInsertKeys<T extends TableDef> = {
  [K in keyof ColumnMap<T>]: ColumnMap<T>[K] extends ColumnDef
    ? IsInsertable<ColumnMap<T>[K]> extends true
      ? IsRequiredInsert<ColumnMap<T>[K]> extends true ? K : never
      : never
    : never;
}[keyof ColumnMap<T>];

/**
 * Keys that are optional for insert (nullable, has default, or optional).
 */
type OptionalInsertKeys<T extends TableDef> = {
  [K in keyof ColumnMap<T>]: ColumnMap<T>[K] extends ColumnDef
    ? IsInsertable<ColumnMap<T>[K]> extends true
      ? IsRequiredInsert<ColumnMap<T>[K]> extends false ? K : never
      : never
    : never;
}[keyof ColumnMap<T>];

/**
 * Create DTO - includes only insertable columns with proper optionality.
 * Auto-generated columns (autoIncrement, generated) are excluded.
 * Columns with defaults or nullable are optional.
 *
 * @example
 * ```ts
 * // Auto-excludes id (autoIncrement), createdAt (has default)
 * type CreateUserDto = CreateDto<typeof User>;
 * // → { name: string; email: string; bio?: string }
 *
 * // Exclude additional fields (e.g., authorId comes from context)
 * type CreatePostDto = CreateDto<typeof Post, 'authorId'>;
 * ```
 */
export type CreateDto<
  T extends TableDef,
  TExclude extends keyof ColumnMap<T> = never
> = Simplify<
  { [K in Exclude<RequiredInsertKeys<T>, TExclude>]: ColumnToTs<ColumnMap<T>[K]> } &
  { [K in Exclude<OptionalInsertKeys<T>, TExclude>]?: ColumnToTs<ColumnMap<T>[K]> }
>;

/**
 * Update DTO - all columns are optional (partial update).
 * Excludes specified columns (e.g., id, createdAt).
 *
 * @example
 * ```ts
 * type UpdateUserDto = UpdateDto<typeof User>;
 * // → { name?: string; email?: string; bio?: string; ... }
 *
 * // Exclude fields that shouldn't be updated
 * type UpdateUserDto = UpdateDto<typeof User, 'id' | 'createdAt'>;
 * ```
 */
export type UpdateDto<
  T extends TableDef,
  TExclude extends keyof ColumnMap<T> = never
> = Simplify<{
  [K in Exclude<keyof ColumnMap<T>, TExclude>]?: ColumnToTs<ColumnMap<T>[K]>;
}>;
