import { deriveIndexName } from '../naming-strategy.js';
import {
  createLiteralFormatter,
  renderIndexColumns
} from '../sql-writing.js';
import {
  composeSchemaDialect,
  createStandardDropColumnCapability,
  createStandardDropTableCapability,
  type SchemaDialectServices
} from '../schema-dialect-composer.js';
import type { SchemaDialect } from '../schema-dialect.js';
import {
  normalizeColumnType,
  renderTypeWithArgs,
  type ColumnDef
} from '../../../schema/column-types.js';
import type { IndexDef, TableDef } from '../../../schema/table.js';
import type { DatabaseTable } from '../schema-types.js';

const quoteIdentifier = (id: string): string => `"${id}"`;
const literalFormatter = createLiteralFormatter();

const renderPostgresColumnType = (
  column: ColumnDef,
  services: SchemaDialectServices
): string => {
  const override = column.dialectTypes?.[services.name] ?? column.dialectTypes?.default;
  if (override) return renderTypeWithArgs(override, column.args);

  const type = normalizeColumnType(column.type);
  switch (type) {
    case 'int':
    case 'integer': return 'integer';
    case 'bigint': return 'bigint';
    case 'uuid': return 'uuid';
    case 'boolean': return 'boolean';
    case 'json': return 'jsonb';
    case 'decimal':
      return column.args?.length ? `numeric(${column.args[0]}, ${column.args[1] ?? 0})` : 'numeric';
    case 'float':
    case 'double': return 'double precision';
    case 'timestamptz': return 'timestamptz';
    case 'timestamp': return 'timestamp';
    case 'date': return 'date';
    case 'datetime': return 'timestamp';
    case 'varchar': return column.args?.length ? `varchar(${column.args[0]})` : 'varchar';
    case 'text': return 'text';
    case 'enum': return 'text';
    case 'binary':
    case 'varbinary':
    case 'blob':
    case 'bytea': return 'bytea';
    case 'vector':
      return column.vectorOptions?.elementType === 'float16'
        ? `halfvec(${column.vectorOptions.dimensions})`
        : column.args?.length
          ? `vector(${column.args[0]})`
          : 'vector';
    case 'halfvec': return column.args?.length ? `halfvec(${column.args[0]})` : 'halfvec';
    default: return renderTypeWithArgs(String(type).toLowerCase(), column.args);
  }
};

const renderPostgresIndex = (
  table: TableDef,
  index: IndexDef,
  services: SchemaDialectServices
): string => {
  const name = index.name || deriveIndexName(table, index);
  let columns = renderIndexColumns(services, index.columns);
  if (index.ops) columns = `${columns} ${index.ops}`;
  const unique = index.unique ? 'UNIQUE ' : '';
  const using = index.using ? ` USING ${index.using}` : '';
  let withClause = '';
  if (index.with) {
    if (typeof index.with === 'string') {
      withClause = ` WITH (${index.with})`;
    } else {
      const params = Object.entries(index.with).map(([key, value]) => `${key} = ${value}`).join(', ');
      withClause = ` WITH (${params})`;
    }
  }
  const where = index.where ? ` WHERE ${index.where}` : '';
  return `CREATE ${unique}INDEX IF NOT EXISTS ${services.quoteIdentifier(name)} ON ${services.formatTableName(table)}${using} (${columns})${withClause}${where};`;
};

export const createPostgresSchemaDialect = (): SchemaDialect =>
  composeSchemaDialect({
    name: 'postgres',
    quoteIdentifier,
    literalFormatter,
    renderColumnType: renderPostgresColumnType,
    renderAutoIncrement: column => {
      if (!column.autoIncrement) return undefined;
      const strategy = column.generated === 'always' ? 'GENERATED ALWAYS' : 'GENERATED BY DEFAULT';
      return `${strategy} AS IDENTITY`;
    },
    renderIndex: renderPostgresIndex,
    renderReferenceSuffix: ref => ref.deferrable ? 'DEFERRABLE INITIALLY DEFERRED' : undefined,
    supportsPartialIndexes: true,
    mutations: services => ({
      dropTable: createStandardDropTableCapability(services),
      dropColumn: createStandardDropColumnCapability(services),
      dropIndex: {
        compile(table, index) {
          const qualified = table.schema
            ? `${services.quoteIdentifier(table.schema)}.${services.quoteIdentifier(index)}`
            : services.quoteIdentifier(index);
          return [`DROP INDEX IF EXISTS ${qualified};`];
        }
      },
      alterColumn: {
        compile(table, column, actualColumn, diff) {
          void actualColumn;
          const statements: string[] = [];
          const tableName = services.formatTableName(table);
          const columnName = services.quoteIdentifier(column.name);

          if (diff.typeChanged) {
            statements.push(
              `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} TYPE ${renderPostgresColumnType(column, services)};`
            );
          }
          if (diff.defaultChanged) {
            statements.push(
              column.default === undefined
                ? `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} DROP DEFAULT;`
                : `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} SET DEFAULT ${services.renderDefault(column.default, column)};`
            );
          }
          if (diff.nullabilityChanged) {
            statements.push(
              `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} ${column.notNull ? 'SET' : 'DROP'} NOT NULL;`
            );
          }
          if (diff.autoIncrementChanged) {
            if (column.autoIncrement) {
              const strategy = column.generated === 'always' ? 'ALWAYS' : 'BY DEFAULT';
              statements.push(
                `ALTER TABLE ${tableName} ALTER COLUMN ${columnName} ADD GENERATED ${strategy} AS IDENTITY;`
              );
            } else {
              statements.push(`ALTER TABLE ${tableName} ALTER COLUMN ${columnName} DROP IDENTITY IF EXISTS;`);
            }
          }
          return statements;
        },
        warning(table, column, actualColumn, diff) {
          void table;
          void column;
          void actualColumn;
          return diff.autoIncrementChanged
            ? 'Altering identity properties may fail if an existing sequence is attached; verify generated column state.'
            : undefined;
        }
      }
    })
  });

/** Ergonomic facade; DDL rendering itself is pure composition. */
export class PostgresSchemaDialect implements SchemaDialect {
  private readonly delegate = createPostgresSchemaDialect();
  readonly name = this.delegate.name;
  readonly mutations = this.delegate.mutations;

  quoteIdentifier(id: string): string { return this.delegate.quoteIdentifier(id); }
  formatTableName(table: TableDef | DatabaseTable): string { return this.delegate.formatTableName(table); }
  renderColumnType(column: ColumnDef): string { return this.delegate.renderColumnType(column); }
  renderDefault(value: unknown, column: ColumnDef): string { return this.delegate.renderDefault(value, column); }
  renderAutoIncrement(column: ColumnDef, table: TableDef): string | undefined {
    return this.delegate.renderAutoIncrement(column, table);
  }
  renderReference(ref: Parameters<SchemaDialect['renderReference']>[0], table: TableDef): string {
    return this.delegate.renderReference(ref, table);
  }
  renderIndex(table: TableDef, index: IndexDef): string { return this.delegate.renderIndex(table, index); }
  renderTableOptions(table: TableDef): string | undefined { return this.delegate.renderTableOptions(table); }
  supportsPartialIndexes(): boolean { return this.delegate.supportsPartialIndexes(); }
  preferInlinePkAutoincrement(column: ColumnDef, table: TableDef, pk: string[]): boolean {
    return this.delegate.preferInlinePkAutoincrement(column, table, pk);
  }
}
